### ISSUE TITLE
Improvements to netconsole

### ISSUE THREAD

**Issue by ricardon** [intel/luv-yocto#129]
By looking at the netconsole scripts, I noticed some areas that might need improvement:

luv-netconsole-params
The file meta-luv/recipes-core/luv-test/luv-test/luv-netconsole-params echo'es a bunch of error messages when netconsole fails to configure. These messages are only printed to stdout. It might be useful to log this messages in the debug file. Perhaps luv-netconsole-params can receive as argument the filename to log debug messages as created by luv-netconsole.

luv-netconsole
When logging, we do the following:
```
gen_error_message
echo some error | tee -a ${LUV_DEBUG_LOG_DIR}
```

It might be better to do it as:
`gen_error_message some error`

and let gen_error_message() do all the work.

Also, gen_error_message() calls gen_debug_file(). This has the effect of creating a new debug file each time we need to log an error. It might be better, if we called gen_debug_file() once when starting the script to create a debug file once and then keep using it for gen_error_message().

**Comment by meghadey** [comment]
This issue has been resolved as part of the above commit. Hence closing it,
