### ISSUE TITLE
Make runqemu understand .img

### ISSUE THREAD

**Issue by mfleming** [intel/luv-yocto#18]
It would be very useful if runqemu could be made to understand how to run the the luv-live image. Currently we have to manually invoke qemu from the build directory when testing out luv-live-image.img, which means we can't make use of all of runqemu's smarts (like the biosdir and publicvnc options, etc).

It should be possible to make changes that are analogous to the .vmdk and .iso code paths, only instead of using -iso we'd need to use -hda.

**Comment by meghadey** [comment]
Check if this issue still exists.

**Comment by meghadey** [comment]
we don't use runqemu any longer, hence closing this issue
