### ISSUE TITLE
BITS: Failed cpu detection is causing bogus MSR failures

### ISSUE THREAD

**Issue by mfleming** [intel/luv-yocto#20]
The CPU detection in BITS has got some issues, as it seems that lots and lots of CPUs are not detected correctly. This lack of detection leads to the MSR consistency test reading MSRs such as the RAPL registers, which are never guaranteed to be consistent across cpus, and we end up with bogus test failures.

Mateus reported some MSR consistency failures on the luv mailing list, https://lists.01.org/pipermail/luv/2014-October/000098.html

@ricardon can you take a look at fixing this? This bug is starting to become a major headache. We need a robust solution to this problem as constantly updating the MSR blacklists as new CPUs are released just doesn't scale. I would have expected the blacklists to be largely the same between CPU families. Alternatively, we could make this a whitelist so if someone runs luvOS on a brand new CPU it won't test any new MSRs for that CPU, but at least we shouldn't see any failures.

Please work with Josh and Burt Triplett (upstream BITS) if necessary to get this fixed.

**Comment by meghadey** [comment]
partially fixed by BITS. Probably need to add new tables.

**Comment by meghadey** [comment]
bits needs to check if newer CPU models have new MSRs or existing MSR addresses have changed on these systems. This requires manual effort everytime a new CPU model arrives.

**Comment by meghadey** [comment]
this will be tracked by another issue i.e to add new CPU models to BITS
