### ISSUE TITLE
Design a mechanism to detect and report system hangs

### ISSUE THREAD

**Issue by ricardon** [intel/luv-yocto#51]
Given that LUV focuses on testing UEFI firmware implementations, such implementations are at different stages of development and stability (i.e., they could have bugs). A firmware bug could cause the system to hang. It could be good for LUV to be able to recover from such hangs and reboot with a recovery configuration.

Additional features would include report the hang to the tester, dump memory, register, point of failure, stack, etc.

**Comment by meghadey** [comment]
@ricardon 
Do you think the telemetrics feature could tackle this issue?

**Comment by ricardon** [comment]
Telemetrics will give us the infrastructure to report things. What we
probably need are the probes to detect these things. Perhaps we can use the
timeout of a non-maskable interrupt. We are especially vulnerable before
launching Linux. This issue came because we were seeing hangs in BITS.
Perhaps we can setup a watchdog timer before running bits and have the
system reboot if it hung. Then, telemetrics would see some indication of
this and issue a report.

**Comment by meghadey** [comment]
add an interrupt handler to bits.

**Comment by meghadey** [comment]
In the recent past, we have only seen BITS appear to fail, on some systems where the call to exit_boot_services(from LUV grub) never returns .

We have added a patchset which lets the user know of this issue and prompt the user to issue a reboot. On rebooting, the BITS test-suite is skipped. Please see below for more details:
https://lists.01.org/pipermail/luv/2018-June/002770.html
