### ISSUE TITLE
LUV needs a dynamic mechanism to continue running tests after error has been detected

### ISSUE THREAD

**Issue by gkammela** [intel/luv-yocto#56]
It is good to have a feature in LUV that dynamically determines whether testing should continue after an error has been detected. For example if the error has been detected in BITS testsuite (which is the first testsuite in the order of execution) and LUV should be able to either continue the next test suite in the order or stop the execution of all test suites. This feature saves time to the tester and eliminates the possibility of the thought that booting LUV  causes system hang and leaves the rest of the results irrelevant. As per Ed's suggestion we can call it a feature that  "stop on error"

**Comment by meghadey** [comment]
In the recent past, we have only seen BITS appear to fail, on some systems where the call to exit_boot_services(from LUV grub) never returns . 

We have added a patchset which lets the user know of this issue and prompt the user to issue a reboot. On rebooting, the BITS test-suite is skipped. Please see below for more details:
https://lists.01.org/pipermail/luv/2018-June/002770.html
