### ISSUE TITLE
Classify test results by severity

### ISSUE THREAD

**Issue by ricardon** [intel/luv-yocto#81]
Not all the errors are born equal. Some issues are more severe than others and require to be looked at closely. For instance, having conflicts in OpRegions is more severe than having default strings in the ACPI tables.

Having a large number of bugs may give a wrong impression of the quality of the firmware if most of them are trivial. Also, giving more prominence to severe bugs helps testers and developers to focus efforts on the most critical ones.

**Comment by ricardon** [comment]
FWTS already provides a mechanism for this. A similar scheme needs to be implemented for the rest of the test suites.

**Comment by meghadey** [comment]
This has been addressed by Ricardo as part of https://lists.01.org/pipermail/luv/2018-March/002637.html and https://lists.01.org/pipermail/luv/2018-March/002647.html
