### ISSUE TITLE
Bits- skipping most of the unittests

### ISSUE THREAD

**Issue by gkammela** [intel/luv-yocto#91]
In the recent findings , bits skips most of the unittests, leaving an exception error. This issue was found in the firmware of HP Elitebook 840. The issue is critical as there is no way of finding the issues in BIOS if bits skips most of the unittests.

**Comment by meghadey** [comment]
is this issue still observed?

**Comment by meghadey** [comment]
Closing this as it is not observed anymore. Can be reopened again if it is observed.
